name: ZSociety
main: com.zixuan007.society.SocietyPlugin
version: "1.0.8alpha"
author: "zixuan007"
api: ["1.0.0"]


permissions:
  society.command.user:
    default: true
  society.command.admin:
    default: op
