# ________  ________  ________  ________  ___  _______  _________    ___    ___
#|\_____  \|\   ____\|\   __  \|\   ____\|\  \|\  ___ \|\___   ___\ |\  \  /  /|
# \|___/  /\ \  \___|\ \  \|\  \ \  \___|\ \  \ \   __/\|___ \  \_| \ \  \/  / /
#     /  / /\ \_____  \ \  \\\  \ \  \    \ \  \ \  \_|/__  \ \  \   \ \    / /
#    /  /_/__\|____|\  \ \  \\\  \ \  \____\ \  \ \  \_|\ \  \ \  \   \/  /  /
#   |\________\____\_\  \ \_______\ \_______\ \__\ \_______\  \ \__\__/  / /
#    \|_______|\_________\|_______|\|_______|\|__|\|_______|   \|__|\___/ /
#             \|_________|                                         \|___|/


版本: "1.0.0"

创建公会金额: 100000

求婚金额: 100000.0

语言: "zh_CN.yml"

聊天显示开启: true

称号格式: "${privilege}§r§7[§6${world}§7][${title}§7][§e${societyName}§7]§7[${marry}§7]§b${playerName}§f❥${message}"

底部显示开启: false

底部格式化: "§c✎手持>${itemID}  §9☣地图>${levelName}  §d♨生命>${h}/${mh}  §f۞在线>${online}/${maxplayer}  §b❉延迟>${ms} \n §2✤职位>${post}
                   §e♈金币>${money}   §7☼公会>${societyName}  §3❤公会等级>${societyGrade}"

玩家标签显示开启: true

玩家名称标签格式: "${privilege}§r §l§3❤§r §e${title} §l§a✤§r §b${societyName} §l§a✤§r §9${name}"

称号商店格式:
  - "§7[§c称§a号§b商店§7]"
  - "§7[§e称号§b☼§f${title}§7]"
  - "§7[售价§b❤§e${money}§7]"
  - "§c快速抢购"

公会商店格式:
  - "§7[§c公§a会§b商店§7]"
  - "§7[§b物品->§a${itemName}§e数量§f:§c${count}§7]"
  - "§7[售价§b❤§e${itemPrice}§7]"
  - "§c所属公会:§a${societyName}"

# 公会等级必须按照等级顺序重小到大,职位等级越小排名越靠前
职位:
  - {
    名称: 会长, #名称
    等级: 1, #职位等级
    数量: 1 #可拥有数量 (会长必须唯一) -1代表无限
  }
  - {
    名称: 副会长,
    等级: 2,
    数量: 1
  }
  - {
    名称: 元老,
    等级: 3,
    数量: 2
  }
  - {
    名称: 精英,
    等级: 4,
    数量: 1
  }

#公会等级
#配置格式如下 公会等级: [最大成员数量,升级所需要的金额]
等级1:
  - 10
  - 1000
等级2:
  - 20
  - 10000
等级3:
  - 30
  - 20000
等级4:
  - 40
  - 40000
等级5:
  - 50
  - 80000
等级6:
  - 60
  - 100000
等级7:
  - 70
  - 1000000

